// Re-export all anilist functions with explicit named exports for deployment validation
export {
  // Anime functions
  getTrending,
  getTop,
  getPopular,
  getTopMovies,
  getLatestMovies,
  getAiringNow,
  getUpcoming,
  getTopThisSeason,
  getHomePageData,
  getMultipleAnimeFromAniList,
  getMediaByAniListId,
  getAnimeEpisodes,
  getAnimeRecommendations,
  getAnimeStaff,
  getAnimeReviews,
  getAnimePictures,
  getAnimeVideos,
  getLatestAdditions,
  // Manga functions
  getTrendingManga,
  getPopularManga,
  getTopManga,
  getReleasingManga,
  getUpcomingManga,
  getMangaStaff,
  getMangaReviews,
  getMangaRecommendations,
  getMangaCharacters,
  // Character functions
  getCharacterDetails,
  getCharacterPictures,
  searchCharacters,
  getCharacter,
  getAnimeCharactersFromAniList,
  getCharacterVoiceActors,
  // Search functions
  searchMediaGraphQL,
  getMediaBySeason,
  getSeasonsList,
  getMediaRelations,
  getLatestMediaCounts,
  getJikanGenresAndThemes,
  // News functions
  getLatestNewsFromAniList,
  getNewsForSpecificAnime,
  getLatestRecommendations,
  // Person functions
  getPersonDetails,
  getPersonPictures,
  // Utils
  fetchAniList,
  jikanApiRequest,
  mapJikanMediaToAnime,
  mapAniListMediaToAnime,
  deduplicateAnime,
} from "../src/lib/anilist/index"
